### ISSUE TITLE
java.lang.NoClassDefFoundError: com/e_gineering/collectd/FastJMX

### ISSUE THREAD

**Issue by devilldog** [egineering-llc/collectd-fast-jmx#30]
Here is my Config and thanks for any help !

```
LoadPlugin java

<Plugin "java">

 JVMARG "-Djava.class.path=/usr/share/collectd/java/collectd-api.jar:/usr/share/collectd/java/collectd-fast-jmx.jar"

  LoadPlugin "com.e_gineering.collectd.FastJMX"

  <Plugin "FastJMX">

    MaxThreads 256
    CollectInternal true

    <MBean "classes">
      ObjectName "java.lang:type=ClassLoading"

      <Value "LoadedClassCount">
        Type "gauge"
        InstancePrefix "loaded_classes"
        PluginName "JVM"
      </Value>
    </MBean>
...................
```

```
 collectd[19249]: java plugin: cjni_config_load_plugin: FindClass (com/e_gineering/collectd/FastJMX) failed.
Jan 26 20:14:19  collectd: Exception in thread "main" java.lang.NoClassDefFoundError: com/e_gineering/collectd/FastJMX
Jan 26 20:14:19  collectd: Caused by: java.lang.ClassNotFoundException: com.e_gineering.collectd.FastJMX
Jan 26 20:14:19  collectd: at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
Jan 26 20:14:19  collectd: at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
Jan 26 20:14:19  collectd: at java.security.AccessController.doPrivileged(Native Method)
Jan 26 20:14:19  collectd[19249]: java plugin: Configuration block for `FastJMX' found, but no such configuration callback has been registered. Please make sure, the `LoadPlugin' lines precede the `Plugin' blocks.
Jan 26 20:14:19  collectd: at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
Jan 26 20:14:19  collectd: at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
Jan 26 20:14:19  collectd: at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
Jan 26 20:14:19  collectd: at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
Jan 26 20:14:19  collectd[19249]: Initialization complete, entering read-loop.
```

**Comment by devilldog** [comment]
contents of the java directory
```
total 2004
drwxr-xr-x  2 root root      85 Jan 26 20:05 .
drwxr-xr-x. 3 root root      32 Jan 26 18:04 ..
-rw-r--r--  1 root root   13465 Dec  6 16:40 collectd-api.jar
-rw-r--r--  1 root root 2015782 Dec  9 22:27 collectd-fast-jmx-1.0.0.jar
-rw-r--r--  1 root root   15880 Dec  6 16:40 generic-jmx.jar
```

**Comment by devilldog** [comment]
Well Solved that problem, the file name in the class path was wrong

**Comment by devilldog** [comment]
but i do get:
```
Jan 26 20:45:17  collectd: Exception in thread "Thread-1" java.lang.NullPointerException
Jan 26 20:45:17  collectd: at com.e_gineering.collectd.FastJMX.config(FastJMX.java:211)
Jan 26 20:45:17  collectd[21837]: Initialization complete, entering read-loop.
Jan 26 20:45:17  collectd[21837]: FastJMX Plugin: Unexpected Throwable: java.lang.NullPointerException
Jan 26 20:45:17  collectd: Jan 26, 2016 8:45:17 PM com.e_gineering.collectd.FastJMX read
Jan 26 20:45:17  collectd: SEVERE: Unexpected Throwable: java.lang.NullPointerException
```

**Comment by devilldog** [comment]
solved again! same as they types.db issue in https://github.com/egineering-llc/collectd-fast-jmx/issues/7

**Comment by bvarner** [comment]
Yeah, I really do need to fix that one. :-)
