### ISSUE TITLE
How to configure collectd-fast-jmx with weblogic servers

### ISSUE THREAD

**Issue by mailRavi** [egineering-llc/collectd-fast-jmx#38]
How to configure collectd-fast-jmx with weblogic server to collect the metrics. any help is appreciated.

Thanks
Ravi

**Comment by ivnilv** [comment]
I'm also interested in that !

**Comment by vutukuribharat** [comment]
I'm also interested 

Here is the log output

Aug 27 14:54:37 ogslab1.1gs.us systemd[1]: Started Collectd statistics daemon.
Aug 27 14:54:38 ogslab1.1gs.us collectd[6567]: java plugin: cjni_config_load_plugin: FindClass (com/e_gineering/collectd/FastJMX) failed.
Aug 27 14:54:38 ogslab1.1gs.us collectd[6567]: Exception in thread "main" java.lang.NoClassDefFoundError: com/e_gineering/collectd/FastJMX
Aug 27 14:54:38 ogslab1.1gs.us collectd[6567]: Caused by: java.lang.ClassNotFoundException: com.e_gineering.collectd.FastJMX
Aug 27 14:54:38 ogslab1.1gs.us collectd[6567]: at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
Aug 27 14:54:38 ogslab1.1gs.us collectd[6567]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
Aug 27 14:54:38 ogslab1.1gs.us collectd[6567]: at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
Aug 27 14:54:38 ogslab1.1gs.us collectd[6567]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Aug 27 14:54:38 ogslab1.1gs.us collectd[6567]: java plugin: Configuration block for `FastJMX' found, but no such configuration c...blocks.
Aug 27 14:54:38 ogslab1.1gs.us collectd[6567]: Initialization complete, entering read-loop.

**Comment by bvarner** [comment]
I personally haven't done JMX with weblogic. I'm sure it could handle it...

@vutukuribharat It looks like you haven't added the collectd-fast-jmx jar to your path.

you'll need to make sure the java plugin block contains a JVMARG with both .jars in the path.
```
LoadPlugin java
<Plugin "java">
  JVMARG "-Djava.class.path=/path/to/collectd-api.jar:/path/to/collectd-fast-jmx.jar"
</Plugin>
```

**Comment by albpal** [comment]
I'm getting the following error with the sample configuration showed at https://github.com/egineering-llc/collectd-fast-jmx.:

> Dec 17 11:21:30 work collectd[28604]: FastJMX Plugin: Unexpected Throwable: java.lang.NullPointerException
> Dec 17 11:21:30 work collectd[28604]: [2018-12-17 11:21:31] FastJMX Plugin: Unexpected Throwable: java.lang.NullPointerException
> Dec 17 11:21:30 work collectd[28604]: Dec 17, 2018 11:21:30 AM com.e_gineering.collectd.FastJMX read
> Dec 17 11:21:30 work collectd[28604]: SEVERE: Unexpected Throwable: java.lang.NullPointerException

The destination JVM is java 1.8

After some debugging, I have seen the null pointer exception is coming when function Collectd.getDS is called when Type "java_memory". I have checked my types.db and there is not such java_memory type. Figuring out what to write down....
